// the-other-shop-node/src/pages/Index.svelte
<script>
  import { onMount } from 'svelte';
  import Navbar from '../components/Navbar.svelte';
  import AnnouncementBar from '../components/AnnouncementBar.svelte';
  import Hero from '../components/Hero.svelte';
  import ProductGrid from '../components/ProductGrid.svelte';
  import LookbookSection from '../components/LookbookSection.svelte';
  import Footer from '../components/Footer.svelte';
  import { loadStoreData } from '../lib/storeData.js';

  let data = null;
  let loading = true;

  onMount(async () => {
    try { data = await loadStoreData(); }
    catch (e) { console.error(e); }
    finally { loading = false; }
  });
</script>

<svelte:head>
  <title>{data ? data.site.name : 'Others.'}</title>
  <meta name="description" content={data ? data.site.description : 'Streetwear rooted in culture, built for everyone else.'} />
</svelte:head>

{#if loading || !data}
  <div class="flex min-h-screen items-center justify-center bg-background">
    <div class="w-6 h-6 border-2 border-foreground/20 border-t-foreground rounded-full animate-spin"></div>
  </div>
{:else}
  <div class="min-h-screen">
    <Navbar siteName={data.site.name} logo={data.site.logo} />
    <Hero hero={data.site.hero} />
    <AnnouncementBar text={data.site.announcement} />
    <ProductGrid products={data.products} currency={data.site.currency} />
    <LookbookSection />
    <Footer site={data.site} />
  </div>
{/if}

// src/pages/Index.tsx
import Navbar from "@/components/Navbar";
import AnnouncementBar from "@/components/AnnouncementBar";
import Hero from "@/components/Hero";
import ProductGrid from "@/components/ProductGrid";
import LookbookSection from "@/components/LookbookSection";
import Footer from "@/components/Footer";
import { useStoreData } from "@/hooks/useStoreData";

const Index = () => {
  const { data, loading } = useStoreData();

  if (loading || !data) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background">
        <div className="w-6 h-6 border-2 border-foreground/20 border-t-foreground rounded-full animate-spin" />
      </div>
    );
  }

  return (
    <div className="min-h-screen">
      <Navbar siteName={data.site.name} />
      <Hero hero={data.site.hero} />
      <AnnouncementBar text={data.site.announcement} />
      <ProductGrid products={data.products} currency={data.site.currency} />
      <LookbookSection />
      <Footer site={data.site} />
    </div>
  );
};

export default Index;
